services:
    bot:
        image: ghcr.io/adrithedev/hypnobot:latest
        restart: unless-stopped
        environment:
            DISCORD_TOKEN: ${DISCORD_TOKEN}
            CLIENT_ID: ${CLIENT_ID}
            OWNER_IDS: ${OWNER_IDS}
            DEV_MODE: false
            DATABASE_URL: ${DATABASE_URL}
            STATUS_WEBHOOK_URL: ${STATUS_WEBHOOK_URL}
